readers:
  - "urn:github:526301"
assets:
  config.yml: yegor256/home#assets/0pdd/config.yml
  id_rsa: yegor256/home#assets/heroku-key
  id_rsa.pub: yegor256/home#assets/heroku-key.pub
install: |-
  sudo gem install pdd -v 0.20.5
  git config --global user.email "server@0pdd.com"
  git config --global user.name "0pdd.com"
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  ruby -v
  bundle install --no-color
release:
  sensitive:
    - config.yml
  script: |-
    pdd -f /dev/null
    bundle exec rake
    git remote add heroku git@heroku.com:zeropdd.git
    rm -rf ~/.ssh
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git fetch
    sed -i "s/BUILD/${tag}/g" ./version.rb
    git add ./version.rb
    git commit -m 'build number set'
    cp ../config.yml config.yml
    git add config.yml
    ruby test/test_credentials.rb
    git commit -m 'config.yml'
    git push -f heroku $(git symbolic-ref --short HEAD):master
    git reset HEAD~1
    rm -rf config.yml
    curl -f --connect-timeout 15 --retry 5 --retry-delay 30 http://www.0pdd.com > /dev/null
merge:
  script: |-
    pdd -f /dev/null
    bundle exec rake
deploy:
  script: |-
    echo 'There is nothing to deploy'
    exit -1
